# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fintak

app: fintak
# "service" is the name of this project. This will also be added to your AWS resource names.
service: identity-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    COGNITO_DEV_CLIENT_ID: ${ssm:/COGNITO_DEV_CLIENT_ID}
    COGNITO_DEV_CLIENT_SECRET: ${ssm:/COGNITO_DEV_CLIENT_SECRET}
    ENV: ${self:provider.stage}

functions:
  reset-password:
    handler: handlers/reset-password.handler
    events:
      - httpApi:
          path: /auth/reset-password
          method: post
  forgot-password:
    handler: handlers/forgot-password.handler
    events:
      - httpApi:
          path: /auth/forgot-password
          method: post
  verification-email:
    handler: handlers/verification-email.handler
    events:
      - httpApi:
          path: /auth/verification-email
          method: post
  login:
    handler: handlers/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: post
  signup:
    handler: handlers/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: post
  logout:
    handler: handlers/logout.handler
    events:
      - httpApi:
          path: /auth/logout
          method: post

resources:
  Resources:
    MyLambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CloudWatchLogsPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
